const fs = require('fs');
const file = 'src/data/hok_heroes.json';
const heroes = JSON.parse(fs.readFileSync(file, 'utf8'));

const nameMap = {
  "元流の子（タンク）": "Yuanliu Child (Tank)",
  "元流の子（メイジ）": "Yuanliu Child (Mage)",
  "后羿": "Hou Yi",
  "廉頗": "Lian Po",
  "ミレディ": "Milady",
  "元流の子（マークスマン）": "Yuanliu Child (Marksman)",
  "カルラ": "Garo",
  "妲己": "Daji",
  "魯班7号": "Luban No.7",
  "アンジェラ": "Angela",
  "小喬": "Xiao Qiao",
  "趙雲": "Zhao Yun",
  "墨子": "Mozi",
  "孫尚香": "Sun Shangxiang",
  "荘子": "Zhuangzi",
  "劉禅": "Liu Shan",
  "漸離": "Gao Jianli",
  "阿軻": "A Ke",
  "鐘無艶": "Zhong Wuyan",
  "孫臏": "Sun Bin",
  "扁鵲": "Bian Que",
  "白起": "Bai Qi",
  "ミーユエ": "Miyue",
  "呂布": "Lu Bu",
  "周瑜": "Zhou Yu",
  "元歌": "Yuan Ge",
  "夏侯惇": "Xiahou Dun",
  "甄姫": "Zhen Ji",
  "ファーティフ": "Fuzi",
  "典韋": "Dian Wei",
  "宮本武蔵": "Musashi Miyamoto",
  "李白": "Li Bai",
  "マルコ・ポーロ": "Marco Polo",
  "仁傑": "Di Renjie",
  "達磨": "Dharma",
  "項羽": "Xiang Yu",
  "司馬懿": "Sima Yi",
  "孔子": "Laozi",
  "関羽": "Guan Yu",
  "貂蝉": "Diaochan",
  "ルナ": "Luna",
  "太公望": "Jiang Ziya",
  "劉邦": "Liu Bang",
  "韓信": "Han Xin",
  "王昭君": "Wang Zhaojun",
  "蘭陵王": "Prince of Lanling",
  "ムーラン": "Mulan",
  "エリン": "Erin",
  "張良": "Zhang Liang",
  "不知火舞": "Mai Shiranui",
  "ドリア": "Doria",
  "ナコルル": "Nakoruru",
  "橘右京": "Ukyo Tachibana",
  "アーサー": "Arthur",
  "孫悟空": "Wukong",
  "ラプール": "Lumburr",
  "劉備": "Liu Bei",
  "張飛": "Zhang Fei",
  "チーシャ": "Zhaojun",
  "李元芳": "Li Yuanfang",
  "虞美人": "Consort Yu",
  "鐘馗": "Zhong Kui",
  "楊貴妃": "Yang Yuhuan",
  "蒼": "Nuwa",
  "楊戩": "Yang Jian",
  "女媧": "Nuwa",
  "ナタク": "Nezha",
  "干将・莫耶": "Ganjiang & Moye",
  "アテナ": "Athena",
  "蔡文姫": "Cai Wenji",
  "東皇太一": "Donghuang Taiyi",
  "鬼谷子": "Guiguzi",
  "孔明": "Zhuge Liang",
  "大喬": "Da Qiao",
  "黄忠": "Huang Zhong",
  "カイザー": "Kaizer",
  "百里玄策": "Baili Xuance",
  "百里守約": "Baili Shouyue",
  "棋星": "Ming Shiyin",
  "モンキ": "Meng Ya",
  "公孫離": "Gongsun Li",
  "明世隠": "Ming Shiyin",
  "タイガー": "Pei",
  "バイロン": "Biron",
  "瑶": "Yao",
  "雲中君": "Yunzhongjun",
  "李信": "Li Xin",
  "伽羅": "Garo",
  "孫策": "Sun Ce",
  "上官婉児": "Shangguan Wan'er",
  "アレン": "Allain",
  "大司命": "Da Siming",
  "白龍": "Bai Long",
  "溟月": "Ming Yue",
  "曜": "Yao",
  "西施": "Xi Shi",
  "蒙牙": "Meng Ya",
  "瀾": "Lan",
  "鏡": "Jing",
  "アグド": "Agudo",
  "啓": "Qi",
  "シャルロット": "Charlotte",
  "ユンエイ": "Yunying",
  "ハロルド": "Harold",
  "アレッシオ": "Alessio",
  "ルアンナ": "Luara",
  "アタ": "Ata",
  "影": "Ying",
  "ハイノ": "Heino",
  "姫小満": "Ji Xiaoman",
  "少司縁": "Shao Siyuan",
  "バタフライ": "Butterfly",
  "デーヴァラ": "Devara"
};

heroes.forEach(h => {
  if (nameMap[h.name]) {
    h.name_en = nameMap[h.name];
  } else if (!h.name_en) {
    // Basic romaji fallback if not in map
    h.name_en = h.name; 
  }
});

fs.writeFileSync(file, JSON.stringify(heroes, null, 2));
console.log('Added name_en to hok_heroes.json');
